server:
  port: 8086
  address: 0.0.0.0
  servlet:
    context-path: /api

spring:
  application:
    name: template-service
    
template:
  # 可写的 layouts.json 路径
  layouts-path: data/layouts.json
  # 新增版式 HTML 保存目录
  html-dir: data/results

management:
  endpoints:
    web:
      exposure:
        include: "*"
